import type { Metadata } from "next";
import NavBar from "./NavBar";
import "@/app/index.scss";
import TanstackProvider from "@/providers/TanstackProvider";
import RecoilRootWrapper from "@/Wrappers/RecoilRootWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <RecoilRootWrapper>
          <TanstackProvider>
            <NavBar />
            <main>{children}</main>
          </TanstackProvider>
        </RecoilRootWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
