import type { Metadata } from "next";
import NavBar from "./NavBar";
import "@/app/index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <div>
          <NavBar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
